title: NAV Component Analyzer
description: Application for c/al code analyze
author: Mirolubov Artiom
e-mail: mirolubov@gmail.com
githubLink: https://github.com/Mirolubov/NAVComponentAnalyzer
version: 1.0.0
captionML: ENU|RUS
charsetName: CP866